# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\uis\change_sg_col.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.button_box.setOrientation(QtCore.Qt.Vertical)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.preview_field = QtWidgets.QLineEdit(Dialog)
        self.preview_field.setGeometry(QtCore.QRect(20, 100, 251, 31))
        self.preview_field.setReadOnly(True)
        self.preview_field.setObjectName("preview_field")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 251, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 251, 16))
        self.label_4.setObjectName("label_4")
        self.sg_cb = QtWidgets.QComboBox(Dialog)
        self.sg_cb.setGeometry(QtCore.QRect(20, 40, 251, 32))
        self.sg_cb.setObjectName("sg_cb")

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept)
        self.button_box.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Выберите семантическую группу:"))
        self.label_4.setText(_translate("Dialog", "Просмотр сочетания:"))
