# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\uis\delete_words_col.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 309)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.preview_field = QtWidgets.QLineEdit(Dialog)
        self.preview_field.setGeometry(QtCore.QRect(10, 270, 251, 31))
        self.preview_field.setReadOnly(True)
        self.preview_field.setObjectName("preview_field")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 251, 16))
        self.label_2.setObjectName("label_2")
        self.word_list = QtWidgets.QListWidget(Dialog)
        self.word_list.setGeometry(QtCore.QRect(10, 30, 251, 211))
        self.word_list.setObjectName("word_list")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Выберите слова для удаления:"))
        self.label_2.setText(_translate("Dialog", "Просмотр сочетания:"))
