# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\uis\navigation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1077, 577)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(10, 40, 821, 521))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.table_label = QtWidgets.QLabel(Form)
        self.table_label.setGeometry(QtCore.QRect(10, 10, 871, 16))
        self.table_label.setObjectName("table_label")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(840, 40, 221, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.buttons = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.buttons.setContentsMargins(0, 0, 0, 0)
        self.buttons.setObjectName("buttons")
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setGeometry(QtCore.QRect(840, 10, 201, 26))
        self.search_btn.setObjectName("search_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.table_label.setText(_translate("Form", "___"))
        self.search_btn.setText(_translate("Form", "Поиск"))
