# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\uis\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 727)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_db_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_db_btn.setGeometry(QtCore.QRect(200, 10, 181, 32))
        self.load_db_btn.setObjectName("load_db_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 21))
        self.label.setObjectName("label")
        self.db_filename_le = QtWidgets.QLineEdit(self.centralwidget)
        self.db_filename_le.setGeometry(QtCore.QRect(210, 60, 161, 21))
        self.db_filename_le.setReadOnly(True)
        self.db_filename_le.setObjectName("db_filename_le")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 100, 1051, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.workspace = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.workspace.setContentsMargins(0, 0, 0, 0)
        self.workspace.setObjectName("workspace")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 90, 1051, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.change_mode_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_mode_btn.setGeometry(QtCore.QRect(892, 10, 171, 32))
        self.change_mode_btn.setObjectName("change_mode_btn")
        self.create_db_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_db_btn.setGeometry(QtCore.QRect(390, 10, 181, 32))
        self.create_db_btn.setObjectName("create_db_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1073, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_db_btn.setText(_translate("MainWindow", "Загрузить базу данных"))
        self.label_2.setText(_translate("MainWindow", "Выбранная база данных:"))
        self.label.setText(_translate("MainWindow", "Выберите базу данных:"))
        self.change_mode_btn.setText(_translate("MainWindow", "___"))
        self.create_db_btn.setText(_translate("MainWindow", "Создать базу данных"))
